
namespace: enqualifyapp

# Image
image:
  repository: dockerhub.io/enverify-api
  tag: "20240813.1"
  pullPolicy: IfNotPresent

# Replica
replicaCount: 1

# Service
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Image
imagePullSecrets:
  - name: dockerhubsecret

# Deployment
strategy:
  type: Recreate

# Container
containerPorts:
  http: 8080

# Volume
volumes:
  appsettingsjs:
    configMap: enqualify-api
  videopvc:
    persistentVolumeClaim:
      claimName: enqualify-api-claim

# Volume
volumeMounts:
  - name: appsettingsjs
    mountPath: /opt/app-root/app/appsettings.json
    subPath: appsettings.json
  - name: videopvc
    mountPath: /opt/app-root/app/files

# Uygulama
application:
  settings:
    customerAppServiceBase: ""
    ffmpegResourceUsage: 50
  database:
    connections:
      default: ""
  tokens:
    auth:
      jwt:
        key: ""
    request:
      sign:
        key: ""