
namespace: enqualifyapp

# Image
image:
  repository: enqurainc/enverify-api
  tag: "20240813.1"
  pullPolicy: IfNotPresent

# Replica
replicaCount: 1

# Service
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Ingress
ingressClassName: nginx
rules:
  host: enqualifyapi.example.com

# Image
#imagePullSecrets:
  #name: dockerhubsecret

# Deployment
strategy:
  type: Recreate

# Container
containerPorts:
  http: 8080

# Volume
#volumeMounts:
  #appsettingsjs:
   # mountPath: /opt/app-root/app/appsettings.json
   # subPath: appsettings.json
  #videopvc:
    #mountPath: /opt/app-root/app/files

# Volume
volumes:
  appsettingsjs:
    configMap: enqualify-api
  videopvc:
    persistentVolumeClaim:
      claimName: enqualify-api-claim

# Uygulama
application:
  settings:
    customerAppServiceBase: ""
    ffmpegResourceUsage: 50
  database:
    connections:
      default: "Server=;Database=;User ID=;Password=;Connection Timeout=30;Encrypt=False;TrustServerCertificate=false"
  tokens:
    auth:
      jwt:
        key: ""
    request:
      sign:
        key: ""