apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: enqualify-api-claim
   namespaces: enqualifyapp
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
       storage: {{ .Values.pvc.resources.requests.storage }}
